name: Lint
on:
  workflow_dispatch:
  pull_request:
    paths: ["**.yml", "**.yaml"]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: tmknom/github-actions-workflows/.github/workflows/lint.yml@v0
