name: Lint
on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/lint.yml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-yaml:
    uses: tmknom/workflows/.github/workflows/lint-yaml.yml@v1
    with:
      yamllint-config: ".yamllint.yml"
  lint-action:
    uses: tmknom/workflows/.github/workflows/lint-action.yml@v1
    with:
      actionlint-ignore-options: >
        "permissions" section should not be empty.
