name: Test
on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/test.yml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run test
        run: |
          echo "fix me"
